package com.adinfi.seven.business.domain;
// Generated 31/01/2014 04:48:00 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TblPreciosPrensa generated by hbm2java
 */
public class TblPreciosPrensa  implements java.io.Serializable {


     private int idPrecPrensa;
     private TblPrensa tblPrensa;
     private Date fechaCarga;
     private String fileName;
     private Set tblPreciosPrensaDets = new HashSet(0);

    public TblPreciosPrensa() {
    }

	
    public TblPreciosPrensa(int idPrecPrensa, TblPrensa tblPrensa, Date fechaCarga, String fileName) {
        this.idPrecPrensa = idPrecPrensa;
        this.tblPrensa = tblPrensa;
        this.fechaCarga = fechaCarga;
        this.fileName = fileName;
    }
    public TblPreciosPrensa(int idPrecPrensa, TblPrensa tblPrensa, Date fechaCarga, String fileName, Set tblPreciosPrensaDets) {
       this.idPrecPrensa = idPrecPrensa;
       this.tblPrensa = tblPrensa;
       this.fechaCarga = fechaCarga;
       this.fileName = fileName;
       this.tblPreciosPrensaDets = tblPreciosPrensaDets;
    }
   
    public int getIdPrecPrensa() {
        return this.idPrecPrensa;
    }
    
    public void setIdPrecPrensa(int idPrecPrensa) {
        this.idPrecPrensa = idPrecPrensa;
    }
    public TblPrensa getTblPrensa() {
        return this.tblPrensa;
    }
    
    public void setTblPrensa(TblPrensa tblPrensa) {
        this.tblPrensa = tblPrensa;
    }
    public Date getFechaCarga() {
        return this.fechaCarga;
    }
    
    public void setFechaCarga(Date fechaCarga) {
        this.fechaCarga = fechaCarga;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public Set getTblPreciosPrensaDets() {
        return this.tblPreciosPrensaDets;
    }
    
    public void setTblPreciosPrensaDets(Set tblPreciosPrensaDets) {
        this.tblPreciosPrensaDets = tblPreciosPrensaDets;
    }




}


