package com.adinfi.seven.business.domain;
// Generated Aug 18, 2016 6:51:25 PM by Hibernate Tools 4.3.1



/**
 * RelFlujoAct generated by hbm2java
 */
public class RelFlujoAct  implements java.io.Serializable {


     private int id;
     private CatActPred catActPred;
     private CatFlujoAct catFlujoAct;
     private int dias;
     private Integer alerta;

    public RelFlujoAct() {
    }

	
    public RelFlujoAct(int id, CatActPred catActPred, CatFlujoAct catFlujoAct, int dias) {
        this.id = id;
        this.catActPred = catActPred;
        this.catFlujoAct = catFlujoAct;
        this.dias = dias;
    }
    public RelFlujoAct(int id, CatActPred catActPred, CatFlujoAct catFlujoAct, int dias, Integer alerta) {
       this.id = id;
       this.catActPred = catActPred;
       this.catFlujoAct = catFlujoAct;
       this.dias = dias;
       this.alerta = alerta;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public CatActPred getCatActPred() {
        return this.catActPred;
    }
    
    public void setCatActPred(CatActPred catActPred) {
        this.catActPred = catActPred;
    }
    public CatFlujoAct getCatFlujoAct() {
        return this.catFlujoAct;
    }
    
    public void setCatFlujoAct(CatFlujoAct catFlujoAct) {
        this.catFlujoAct = catFlujoAct;
    }
    public int getDias() {
        return this.dias;
    }
    
    public void setDias(int dias) {
        this.dias = dias;
    }
    public Integer getAlerta() {
        return this.alerta;
    }
    
    public void setAlerta(Integer alerta) {
        this.alerta = alerta;
    }




}


