package com.adinfi.seven.business.domain;
/** Generated 4/02/2014 05:03:32 PM by Hibernate Tools 3.6.0*/



/**
 * TblImageArticulo generated by hbm2java
 */
public class TblImageArticulo  implements java.io.Serializable {

	private static final long serialVersionUID = 2795355762499018653L;
     private int idImageArt;
     private TblImagenes tblImagenes;
     private String pathDesc;
     private String idArticulo;
     private String item;

    public TblImageArticulo() {
    }

	
    public TblImageArticulo(int idImageArt, TblImagenes tblImagenes, String idArticulo) {
        this.idImageArt = idImageArt;
        this.tblImagenes = tblImagenes;
        this.idArticulo = idArticulo;
    }
    public TblImageArticulo(int idImageArt, TblImagenes tblImagenes, String pathDesc, String idArticulo, String item) {
       this.idImageArt = idImageArt;
       this.tblImagenes = tblImagenes;
       this.pathDesc = pathDesc;
       this.idArticulo = idArticulo;
       this.item = item;
    }
   
    public int getIdImageArt() {
        return this.idImageArt;
    }
    
    public void setIdImageArt(int idImageArt) {
        this.idImageArt = idImageArt;
    }
    public TblImagenes getTblImagenes() {
        return this.tblImagenes;
    }
    
    public void setTblImagenes(TblImagenes tblImagenes) {
        this.tblImagenes = tblImagenes;
    }
    public String getPathDesc() {
        return this.pathDesc;
    }
    
    public void setPathDesc(String pathDesc) {
        this.pathDesc = pathDesc;
    }
    public String getIdArticulo() {
        return this.idArticulo;
    }
    
    public void setIdArticulo(String idArticulo) {
        this.idArticulo = idArticulo;
    }
    public String getItem() {
        return this.item;
    }
    
    public void setItem(String item) {
        this.item = item;
    }




}


