package com.adinfi.seven.business.domain;

/**
 * CatCategory generated by hbm2java
 */
public class CatCategory_bkp implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3013908940588455209L;

	private Integer categoryId;
	private String code;
	private CatDepto catDepto;
	private Boolean esMercancia = false;

	public CatCategory_bkp() {
	}

	public CatCategory_bkp(Integer categoryId, String code, CatDepto catDepto,
			Boolean esMercancia) {
		super();
		this.categoryId = categoryId;
		this.code = code;
		this.catDepto = catDepto;
		this.esMercancia = esMercancia;
	}

	public Integer getCategoryId() {
		return categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public CatDepto getCatDepto() {
		return catDepto;
	}

	public void setCatDepto(CatDepto catDepto) {
		this.catDepto = catDepto;
	}

	public Boolean getEsMercancia() {
		return esMercancia;
	}

	public void setEsMercancia(Boolean esMercancia) {
		this.esMercancia = esMercancia;
	}

	@Override
	public String toString() {
		return "CatCategory [categoryId=" + categoryId + ", code=" + code
				+ ", catDepto=" + catDepto + ", esMercancia=" + esMercancia
				+ "]";
	}

}