package com.adinfi.seven.business.domain;

import com.adinfi.seven.presentation.views.util.Constants;

// Generated 15/01/2014 11:03:37 AM by Hibernate Tools 3.2.1.GA



/**
 * TblArticulosEspaciosId generated by hbm2java
 */
public class TblArticulosEspaciosId  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 9080676053579375449L;
	private String idArticulo;
     private int idPrensa;
     private int idEspacio;

    public TblArticulosEspaciosId() {
    }

    public TblArticulosEspaciosId(String idArticulo, int idPrensa, int idEspacio) {
       this.idArticulo = idArticulo;
       this.idPrensa = idPrensa;
       this.idEspacio = idEspacio;
    }
   
    public String getIdArticulo() {
        return this.idArticulo;
    }
    
    public void setIdArticulo(String idArticulo) {
        this.idArticulo = idArticulo;
    }
    public int getIdPrensa() {
        return this.idPrensa;
    }
    
    public void setIdPrensa(int idPrensa) {
        this.idPrensa = idPrensa;
    }
    public int getIdEspacio() {
        return this.idEspacio;
    }
    
    public void setIdEspacio(int idEspacio) {
        this.idEspacio = idEspacio;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblArticulosEspaciosId) ) return false;
		 TblArticulosEspaciosId castOther = ( TblArticulosEspaciosId ) other; 
         
		 return ( (this.getIdArticulo()==castOther.getIdArticulo()) || ( this.getIdArticulo()!=null && castOther.getIdArticulo()!=null && this.getIdArticulo().equals(castOther.getIdArticulo()) ) )
 && (this.getIdPrensa()==castOther.getIdPrensa())
 && (this.getIdEspacio()==castOther.getIdEspacio());
   }
   
   public int hashCode() {
         int result = Constants.DIECISIETE;
         
         result = Constants.TREINTAYSIETE * result + ( getIdArticulo() == null ? Constants.ZERO : this.getIdArticulo().hashCode() );
         result = Constants.TREINTAYSIETE * result + this.getIdPrensa();
         result = Constants.TREINTAYSIETE * result + this.getIdEspacio();
         return result;
   }   


}


