package com.adinfi.seven.business.domain;

import java.util.HashSet;
import java.util.Set;

/**
 * CatEtiquetas generated by hbm2java
 */
public class CatEtiquetas implements java.io.Serializable {

    private int idetiqueta;
    private String nombre;
    private String codigo;
    private Set<TblCampana> tblCampanas = new HashSet<TblCampana>(0);

    public CatEtiquetas() {
    }

    public CatEtiquetas(int idetiqueta, String nombre, String codigo) {
        this.idetiqueta = idetiqueta;
        this.nombre = nombre;
        this.codigo = codigo;
    }

    public CatEtiquetas(int idetiqueta, String nombre, String codigo, Set<TblCampana> tblCampanas) {
        this.idetiqueta = idetiqueta;
        this.nombre = nombre;
        this.codigo = codigo;
        this.tblCampanas = tblCampanas;
    }

    public int getIdetiqueta() {
        return this.idetiqueta;
    }

    public void setIdetiqueta(int idetiqueta) {
        this.idetiqueta = idetiqueta;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public Set<TblCampana> getTblCampanas() {
        return this.tblCampanas;
    }

    public void setTblCampanas(Set<TblCampana> tblCampanas) {
        this.tblCampanas = tblCampanas;
    }

}
