package com.adinfi.seven.business.domain;

// Generated 19/08/2013 10:38:14 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * CatRegValues generated by hbm2java
 */
public class CatRegValues implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private int catRegValId = 0;
	private CatAttrs catAttrs;

	private CatRegs catRegId;
	private Date updateDate;
	private String value;

	public CatRegValues() {
	}

	public CatRegValues(int catRegValId, CatAttrs catAttrs, CatRegs catRegId) {
		this.catRegValId = catRegValId;
		this.catAttrs = catAttrs;
		this.catRegId = catRegId;
	}

	public CatRegValues(int catRegValId, CatAttrs catAttrs, CatRegs catRegId,
			Date updateDate, String value) {
		this.catRegValId = catRegValId;
		this.catAttrs = catAttrs;
		this.catRegId = catRegId;
		this.updateDate = updateDate;
		this.value = value;
	}

	public int getCatRegValId() {
		return this.catRegValId;
	}

	public void setCatRegValId(int catRegValId) {
		this.catRegValId = catRegValId;
	}

	public CatAttrs getCatAttrs() {
		return this.catAttrs;
	}

	public void setCatAttrs(CatAttrs catAttrs) {
		this.catAttrs = catAttrs;
	}

	public CatRegs getCatRegId() {
		return this.catRegId;
	}

	public void setCatRegId(CatRegs catRegId) {
		this.catRegId = catRegId;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Override
	public String toString() {
		return "catRegId=" + this.catRegId + " catRegValId=" + this.catRegValId
				+ " value=" + this.value;
	}

}
