package com.adinfi.seven.business.domain;
// Generated Sep 29, 2014 11:31:29 AM by Hibernate Tools 3.6.0



/**
 * RelGrupoZona generated by hbm2java
 */
public class RelGrupoZona  implements java.io.Serializable {


     private int grupoId;
     private TblMecanica tblMecanica;

    public RelGrupoZona() {
    }

    public RelGrupoZona(int grupoId, TblMecanica tblMecanica) {
       this.grupoId = grupoId;
       this.tblMecanica = tblMecanica;
    }
   
    public int getGrupoId() {
        return this.grupoId;
    }
    
    public void setGrupoId(int grupoId) {
        this.grupoId = grupoId;
    }
    public TblMecanica getTblMecanica() {
        return this.tblMecanica;
    }
    
    public void setTblMecanica(TblMecanica tblMecanica) {
        this.tblMecanica = tblMecanica;
    }




}


