package com.adinfi.seven.business.domain;
// Generated Aug 18, 2016 6:51:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * CatActPred generated by hbm2java
 */
public class CatActPred  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private Integer nivelEscalable;
     private Integer orden;
     private CatRole role;
     private Set<RelFlujoAct> relFlujoActs = new HashSet<RelFlujoAct>(0);

    public CatActPred() {
    }

	
    public CatActPred(int id) {
        this.id = id;
    }
    public CatActPred(int id, String descripcion, Integer nivelEscalable, Integer orden, Set<RelFlujoAct> relFlujoActs) {
       this.id = id;
       this.descripcion = descripcion;
       this.nivelEscalable = nivelEscalable;
       this.orden = orden;
       this.relFlujoActs = relFlujoActs;
    }

    @Override
    public String toString() {
        return descripcion;
    }

    @Override
    public boolean equals(Object object) {
        if (this == object) return true;
        if (object == null || getClass() != object.getClass()) return false;
        CatActPred actPred = (CatActPred) object;
        return id == actPred.id;
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getNivelEscalable() {
        return this.nivelEscalable;
    }
    
    public void setNivelEscalable(Integer nivelEscalable) {
        this.nivelEscalable = nivelEscalable;
    }
    public Integer getOrden() {
        return this.orden;
    }
    
    public void setOrden(Integer orden) {
        this.orden = orden;
    }
    public Set<RelFlujoAct> getRelFlujoActs() {
        return this.relFlujoActs;
    }
    
    public void setRelFlujoActs(Set<RelFlujoAct> relFlujoActs) {
        this.relFlujoActs = relFlujoActs;
    }

    public CatRole getRole() {
        return role;
    }

    public void setRole(CatRole role) {
        this.role = role;
    }
}


