package com.adinfi.seven.business.domain;




/**
 * CatProveedor generated by hbm2java
 */
public class CatProveedor_bkp  implements java.io.Serializable {

    private Integer proveedorId;
    private String code;
//    private Set<CatItem> catItems = new HashSet<CatItem>(0);
//    private Set<CatListDet> catListDets = new HashSet<CatListDet>(0);
    
    public CatProveedor_bkp() {
    }

    public CatProveedor_bkp(Integer proveedorId, String code) {
        this.proveedorId = proveedorId;
        this.code = code;
    }

/*    public CatProveedor(Integer proveedorId, String code,CatCategory catCategory,String itemId,
    		 CatSubCategory catSubCategory) { 
        this.proveedorId = proveedorId;
        this.code = code;
        this.catListDets = catListDets;
        this.catItems = catItems; 
    } */

    public Integer getProveedorId() {
        return proveedorId;
    }

    public void setProveedorId(Integer proveedorId) {
        this.proveedorId = proveedorId;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

/*	public Set<CatItem> getCatItems() {
		return catItems;
	}

	public void setCatItems(Set<CatItem> catItems) {
		this.catItems = catItems;
	}

	public Set<CatListDet> getCatListDets() {
		return this.catListDets;
	}

	public void setCatListDets(Set<CatListDet> catListDets) {
		this.catListDets = catListDets;
	}
	*/
}


