package com.adinfi.seven.business.domain;

import com.adinfi.seven.presentation.views.util.Constants;
// Generated 16/01/2014 10:20:42 AM by Hibernate Tools 3.2.1.GA



/**
 * TblPrensaSistemaVentaId generated by hbm2java
 */
public class TblPrensaSistemaVentaId  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 6498474450052110193L;
	private int idPrensa;
     private int idSistemaVenta;

    public TblPrensaSistemaVentaId() {
    }

    public TblPrensaSistemaVentaId(int idPrensa, int idSistemaVenta) {
       this.idPrensa = idPrensa;
       this.idSistemaVenta = idSistemaVenta;
    }
   
    public int getIdPrensa() {
        return this.idPrensa;
    }
    
    public void setIdPrensa(int idPrensa) {
        this.idPrensa = idPrensa;
    }
    public int getIdSistemaVenta() {
        return this.idSistemaVenta;
    }
    
    public void setIdSistemaVenta(int idSistemaVenta) {
        this.idSistemaVenta = idSistemaVenta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblPrensaSistemaVentaId) ) return false;
		 TblPrensaSistemaVentaId castOther = ( TblPrensaSistemaVentaId ) other; 
         
		 return (this.getIdPrensa()==castOther.getIdPrensa())
 && (this.getIdSistemaVenta()==castOther.getIdSistemaVenta());
   }
   
   public int hashCode() {
         int result = Constants.DIECISIETE;
         
         result = Constants.TREINTAYSIETE * result + this.getIdPrensa();
         result = Constants.TREINTAYSIETE * result + this.getIdSistemaVenta();
         return result;
   }   


}


