package com.adinfi.seven.business.domain;

// Generated 19/08/2013 10:38:14 AM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Catalogs generated by hbm2java
 */
public class Catalogs implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private int catId;
	private String catName;
	private String descrip;
	private Character estatus;
	private Set<CatView> catViewForCatId = new HashSet<CatView>(0);

	public Catalogs() {
	}

	public Catalogs(int catId, String catName) {
		this.catId = catId;
		this.catName = catName;
	}

	public int getCatId() {
		return this.catId;
	}

	public void setCatId(int catId) {
		this.catId = catId;
	}

	public String getCatName() {
		return this.catName;
	}

	public void setCatName(String catName) {
		this.catName = catName;
	}

	public String getDescrip() {
		return this.descrip;
	}

	public void setDescrip(String descrip) {
		this.descrip = descrip;
	}

	public Character getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Character estatus) {
		this.estatus = estatus;
	}

	public Set<CatView> getCatViewForCatId() {
		return catViewForCatId;
	}

	public void setCatViewForCatId(Set<CatView> catViewForCatId) {
		this.catViewForCatId = catViewForCatId;
	}
}
