package com.adinfi.seven.business.domain;


/**
* RelUsuariosCategorias generated by hbm2java
*/
public class RelUsuariosCategorias implements java.io.Serializable {

	 /**
	 * 
	 */
	private static final long serialVersionUID = -7284689088282695487L;
	private int idRel;
     private CatCategory catCategory;
     private CatUsuarios catUsuarios;

    public RelUsuariosCategorias() {
    }

	
    public RelUsuariosCategorias(int idRel) {
        this.idRel = idRel;
    }
    public RelUsuariosCategorias(int idRel, CatCategory catCategory, CatUsuarios catUsuarios) {
       this.idRel = idRel;
       this.catCategory = catCategory;
       this.catUsuarios = catUsuarios;
    }
   
    public int getIdRel() {
        return this.idRel;
    }
    
    public void setIdRel(int idRel) {
        this.idRel = idRel;
    }
    public CatCategory getCatCategory() {
        return this.catCategory;
    }
    
    public void setCatCategory(CatCategory catCategory) {
        this.catCategory = catCategory;
    }
    public CatUsuarios getCatUsuarios() {
        return this.catUsuarios;
    }
    
    public void setCatUsuarios(CatUsuarios catUsuarios) {
        this.catUsuarios = catUsuarios;
    }
}
