package com.adinfi.seven.business.domain;

import java.util.HashSet;
import java.util.Set;

/**
 * CatDepto generated by hbm2java
 */
public class CatDepto implements java.io.Serializable {

	private static final long serialVersionUID = 4102947083731706503L;
	private int idDepto;
    private String code;
    private boolean esMercancia;
    private Set<CatCategory> catCategories = new HashSet<CatCategory>(0);

   public CatDepto() {
   }

	
   public CatDepto(int idDepto, boolean esMercancia) {
       this.idDepto = idDepto;
       this.esMercancia = esMercancia;
   }
   public CatDepto(int idDepto, String code, boolean esMercancia, Set<CatCategory> catCategories) {
      this.idDepto = idDepto;
      this.code = code;
      this.esMercancia = esMercancia;
      this.catCategories = catCategories;
   }
  
   public int getIdDepto() {
       return this.idDepto;
   }
   
   public void setIdDepto(int idDepto) {
       this.idDepto = idDepto;
   }
   public String getCode() {
       return this.code;
   }
   
   public void setCode(String code) {
       this.code = code;
   }
   public boolean isEsMercancia() {
       return this.esMercancia;
   }
   
   public void setEsMercancia(boolean esMercancia) {
       this.esMercancia = esMercancia;
   }
   public Set<CatCategory> getCatCategories() {
       return this.catCategories;
   }
   
   public void setCatCategories(Set<CatCategory> catCategories) {
       this.catCategories = catCategories;
   }

}
