package com.adinfi.seven.business.domain;

import java.util.HashSet;
import java.util.Set;

// Generated Jan 21, 2016 12:30:53 PM by Hibernate Tools 4.3.1


/**
 * CatUsuarios generated by hbm2java
 */
public class CatUsuarios  implements java.io.Serializable {

	private static final long serialVersionUID = 8888714519732788956L;
	private int idusuarios;
    private CatRole catRole;
    private String nombre;
    private String nempleado;
    private String plastName;
    private String mlastName;
    private String email;
    private String login;
    private String password;
    private int inactive;
    private int islevel1;
    private int nchange;
    private int idjefe;
    private Set<RelUsuariosCategorias> relUsuariosCategoriases = new HashSet<RelUsuariosCategorias>(0);

   public CatUsuarios() {
   }

	
   public CatUsuarios(int idusuarios, CatRole catRole, String nombre, String nempleado, String plastName, String mlastName, int inactive, int islevel1, int nchange, int idjefe) {
       this.idusuarios = idusuarios;
       this.catRole = catRole;
       this.nombre = nombre;
       this.nempleado = nempleado;
       this.plastName = plastName;
       this.mlastName = mlastName;
       this.inactive = inactive;
       this.islevel1 = islevel1;
       this.nchange = nchange;
       this.idjefe = idjefe;
   }
   public CatUsuarios(int idusuarios, CatRole catRole, String nombre, String nempleado, String plastName, String mlastName, String email, String login, String password, int inactive, int islevel1, int nchange, int idjefe, Set<RelUsuariosCategorias> relUsuariosCategoriases) {
      this.idusuarios = idusuarios;
      this.catRole = catRole;
      this.nombre = nombre;
      this.nempleado = nempleado;
      this.plastName = plastName;
      this.mlastName = mlastName;
      this.email = email;
      this.login = login;
      this.password = password;
      this.inactive = inactive;
      this.islevel1 = islevel1;
      this.nchange = nchange;
      this.idjefe = idjefe;
      this.relUsuariosCategoriases = relUsuariosCategoriases;
   }
    
    
   
    @Override
	public String toString() {
		return nombre + " " + plastName + " " + mlastName ;
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + idusuarios;
		return result;
	}


	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CatUsuarios other = (CatUsuarios) obj;
		if (idusuarios != other.idusuarios)
			return false;
		return true;
	}


	public int getIdusuarios() {
        return this.idusuarios;
    }
    
    public void setIdusuarios(int idusuarios) {
        this.idusuarios = idusuarios;
    }
    public CatRole getCatRole() {
        return this.catRole;
    }
    
    public void setCatRole(CatRole catRole) {
        this.catRole = catRole;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getNempleado() {
		return nempleado;
	}


	public void setNempleado(String nempleado) {
		this.nempleado = nempleado;
	}


	public String getPlastName() {
        return this.plastName;
    }
    
    public void setPlastName(String plastName) {
        this.plastName = plastName;
    }
    public String getMlastName() {
        return this.mlastName;
    }
    
    public void setMlastName(String mlastName) {
        this.mlastName = mlastName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getInactive() {
        return this.inactive;
    }
    
    public void setInactive(int inactive) {
        this.inactive = inactive;
    }
    public int getIslevel1() {
        return this.islevel1;
    }
    
    public void setIslevel1(int islevel1) {
        this.islevel1 = islevel1;
    }
    public int getNchange() {
        return this.nchange;
    }
    
    public void setNchange(int nchange) {
        this.nchange = nchange;
    }
    public int getIdjefe() {
        return this.idjefe;
    }
    
    public void setIdjefe(int idjefe) {
        this.idjefe = idjefe;
    }
    public Set<RelUsuariosCategorias> getRelUsuariosCategoriases() {
        return this.relUsuariosCategoriases;
    }
    
    public void setRelUsuariosCategoriases(Set<RelUsuariosCategorias> relUsuariosCategoriases) {
        this.relUsuariosCategoriases = relUsuariosCategoriases;
    }

    




}


