package com.adinfi.seven.business.domain;

// Generated 15/01/2014 11:03:37 AM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;

/**
 * TblArticulosEspacios generated by hbm2java
 */
public class TblArticulosEspacios implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5120504261872763221L;
	private TblArticulosEspaciosId id;
	private TblPrensa tblPrensa;
	private TblImageArticulo tblImageArticulo;
	private Integer segmentParentId;
	private Integer segmentId;
	private BigDecimal precioPromocion;

	public TblArticulosEspacios() {
	}

	public TblArticulosEspacios(TblArticulosEspaciosId id, TblPrensa tblPrensa,
			TblImageArticulo tblImageArticulo) {
		this.id = id;
		this.tblPrensa = tblPrensa;
		this.tblImageArticulo = tblImageArticulo;
	}

	public TblArticulosEspacios(TblArticulosEspaciosId id, TblPrensa tblPrensa,
			TblImageArticulo tblImageArticulo, Integer segmentParentId,
			Integer segmentId, BigDecimal precioPromocion) {
		this.id = id;
		this.tblPrensa = tblPrensa;
		this.tblImageArticulo = tblImageArticulo;
		this.segmentParentId = segmentParentId;
		this.segmentId = segmentId;
		this.precioPromocion = precioPromocion;
	}

	public TblArticulosEspaciosId getId() {
		return this.id;
	}

	public void setId(TblArticulosEspaciosId id) {
		this.id = id;
	}

	public TblPrensa getTblPrensa() {
		return this.tblPrensa;
	}

	public void setTblPrensa(TblPrensa tblPrensa) {
		this.tblPrensa = tblPrensa;
	}

	public TblImageArticulo getTblImageArticulo() {
		return this.tblImageArticulo;
	}

	public void setTblImageArticulo(TblImageArticulo tblImageArticulo) {
		this.tblImageArticulo = tblImageArticulo;
	}

	public Integer getSegmentParentId() {
		return this.segmentParentId;
	}

	public void setSegmentParentId(Integer segmentParentId) {
		this.segmentParentId = segmentParentId;
	}

	public Integer getSegmentId() {
		return this.segmentId;
	}

	public void setSegmentId(Integer segmentId) {
		this.segmentId = segmentId;
	}

	public BigDecimal getPrecioPromocion() {
		return this.precioPromocion;
	}

	public void setPrecioPromocion(BigDecimal precioPromocion) {
		this.precioPromocion = precioPromocion;
	}

}
