package com.adinfi.seven.business.domain;

// Generated 19/08/2013 10:38:14 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;

/**
 * CatRegs generated by hbm2java
 */
public class CatRegs implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private int catRegId = 0;
	private Catalogs catalogs = null;
	private Date insertDate;
	private Date updateDate;

	private Character estatus;
	private Set<CatRegValues> regValues = new HashSet<CatRegValues>(0);

	public CatRegs(int catRegId, Catalogs catalogs, Date insertDate,
			Date updateDate, Character estatus, Set<CatRegValues> regValues) {
		this.catRegId = catRegId;
		this.catalogs = catalogs;
		this.insertDate = insertDate;
		this.updateDate = updateDate;
		this.estatus = estatus;
		this.regValues = regValues;
	}

	public CatRegs() {
	}

	public Map<String, String> getValuesAsMap(){
		Map<String, String> mapValues=new  TreeMap<String, String>();
		String attrName;
		if(regValues!=null  ){
						 
			for (CatRegValues regVals : regValues) {
				attrName = regVals.getCatAttrs().getAttribs().getAttrName();
				if (attrName == null || attrName.isEmpty()){
					continue;
				}	
				mapValues.put( attrName , regVals.getValue() );								
			}								
		}
		return mapValues;		
		
	}
	
	public int getCatRegId() {
		return this.catRegId;
	}

	public void setCatRegId(int catRegId) {
		this.catRegId = catRegId;
	}

	public Catalogs getCatalogs() {
		return this.catalogs;
	}

	public void setCatalogs(Catalogs catalogs) {
		this.catalogs = catalogs;
	}

	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Character getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Character estatus) {
		this.estatus = estatus;
	}

	public Set<CatRegValues> getRegValues() {
		return regValues;
	}

	public void setRegValues(Set<CatRegValues> regValues) {
		this.regValues = regValues;
	}

	@Override
	public String toString() {
		return "regVals=" + this.catRegId + " regValues="
				+ (this.regValues != null ? this.regValues.size() : 0);
	}
}