package com.adinfi.seven.business.domain;
// Generated Sep 29, 2014 11:31:29 AM by Hibernate Tools 3.6.0



/**
 * RelStore generated by hbm2java
 */
public class RelStore  implements java.io.Serializable {


     private int storeId;
     private TblMecanica tblMecanica;

    public RelStore() {
    }

    public RelStore(int storeId, TblMecanica tblMecanica) {
       this.storeId = storeId;
       this.tblMecanica = tblMecanica;
    }
   
    public int getStoreId() {
        return this.storeId;
    }
    
    public void setStoreId(int storeId) {
        this.storeId = storeId;
    }
    public TblMecanica getTblMecanica() {
        return this.tblMecanica;
    }
    
    public void setTblMecanica(TblMecanica tblMecanica) {
        this.tblMecanica = tblMecanica;
    }




}


