package com.adinfi.seven.business.domain;
// Generated 20/02/2014 07:05:11 PM by Hibernate Tools 3.6.0



/**
 * TblFolletoSistemaVentaId generated by hbm2java
 */
public class TblFolletoSistemaVentaId  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 2572515696081012382L;
	private int idFolleto;
     private int idSistemaVenta;

    public TblFolletoSistemaVentaId() {
    }

    public TblFolletoSistemaVentaId(int idFolleto, int idSistemaVenta) {
       this.idFolleto = idFolleto;
       this.idSistemaVenta = idSistemaVenta;
    }
   
    public int getIdFolleto() {
        return this.idFolleto;
    }
    
    public void setIdFolleto(int idFolleto) {
        this.idFolleto = idFolleto;
    }
    public int getIdSistemaVenta() {
        return this.idSistemaVenta;
    }
    
    public void setIdSistemaVenta(int idSistemaVenta) {
        this.idSistemaVenta = idSistemaVenta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblFolletoSistemaVentaId) ) return false;
		 TblFolletoSistemaVentaId castOther = ( TblFolletoSistemaVentaId ) other; 
         
		 return (this.getIdFolleto()==castOther.getIdFolleto())
 && (this.getIdSistemaVenta()==castOther.getIdSistemaVenta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdFolleto();
         result = 37 * result + this.getIdSistemaVenta();
         return result;
   }   


}


