package com.adinfi.seven.business.domain;
// Generated Jan 21, 2016 12:30:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CatRole generated by hbm2java
 */
public class CatRole  implements java.io.Serializable {


     private int idrole;
     private String desc;
     private Set<CatUsuarios> catUsuarioses = new HashSet<CatUsuarios>(0);

    public CatRole() {
    }

	
    public CatRole(int idrole, String desc) {
        this.idrole = idrole;
        this.desc = desc;
    }
    public CatRole(int idrole, String desc, Set<CatUsuarios> catUsuarioses) {
       this.idrole = idrole;
       this.desc = desc;
       this.catUsuarioses = catUsuarioses;
    }
   
    public int getIdrole() {
        return this.idrole;
    }
    
    public void setIdrole(int idrole) {
        this.idrole = idrole;
    }
    public String getDesc() {
        return this.desc;
    }
    
    public void setDesc(String desc) {
        this.desc = desc;
    }
    public Set<CatUsuarios> getCatUsuarioses() {
        return this.catUsuarioses;
    }
    
    public void setCatUsuarioses(Set<CatUsuarios> catUsuarioses) {
        this.catUsuarioses = catUsuarioses;
    }

    

	@Override
	public String toString() {
		return  desc;
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + idrole;
		return result;
	}


	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CatRole other = (CatRole) obj;
		if (idrole != other.idrole)
			return false;
		return true;
	}

    


}


