package com.adinfi.seven.business.domain;
// Generated 10-ago-2015 17:57:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CatStore generated by hbm2java
 */
public class CatStore  implements java.io.Serializable {


     private int idStore;
     private String code;
     private Integer idCampo;
     private String formatoTienda;
     private String esBase;
     private Set<RelZoneStore> relZoneStores = new HashSet<>(0);

    public CatStore() {
    }

    public CatStore(int idStore) {
        super();
        this.idStore = idStore;
    }

    
	
    public CatStore(int idStore, String code) {
        this.idStore = idStore;
        this.code = code;
    }
    public CatStore(int idStore, String code, Integer idCampo, String formatoTienda, String esBase, Set<RelZoneStore> relZoneStores) {
       this.idStore = idStore;
       this.code = code;
       this.idCampo = idCampo;
       this.formatoTienda = formatoTienda;
       this.esBase = esBase;
       this.relZoneStores = relZoneStores;
    }
   
    public int getIdStore() {
        return this.idStore;
    }
    
    public void setIdStore(int idStore) {
        this.idStore = idStore;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public Integer getIdCampo() {
        return this.idCampo;
    }
    
    public void setIdCampo(Integer idCampo) {
        this.idCampo = idCampo;
    }
    public String getFormatoTienda() {
        return this.formatoTienda;
    }
    
    public void setFormatoTienda(String formatoTienda) {
        this.formatoTienda = formatoTienda;
    }
    public String getEsBase() {
        return this.esBase;
    }
    
    public void setEsBase(String esBase) {
        this.esBase = esBase;
    }
    public Set<RelZoneStore> getRelZoneStores() {
        return this.relZoneStores;
    }
    
    public void setRelZoneStores(Set<RelZoneStore> relZoneStores) {
        this.relZoneStores = relZoneStores;
    }




}


