package com.adinfi.seven.business.domain;
// Generated Sep 29, 2014 11:31:29 AM by Hibernate Tools 3.6.0


/**
 * TblPrograma generated by hbm2java
 */
public class TblPrograma implements java.io.Serializable {


    private int programaId;
    private TblMecanica tblMecanica;

    public TblPrograma() {
    }

    public TblPrograma(int programaId, TblMecanica tblMecanica) {
        this.programaId = programaId;
        this.tblMecanica = tblMecanica;
    }

    public int getProgramaId() {
        return this.programaId;
    }

    public void setProgramaId(int programaId) {
        this.programaId = programaId;
    }

    public TblMecanica getTblMecanica() {
        return this.tblMecanica;
    }

    public void setTblMecanica(TblMecanica tblMecanica) {
        this.tblMecanica = tblMecanica;
    }


}


