package com.adinfi.seven.business.domain;

// Generated 26/10/2013 09:27:46 PM by Hibernate Tools 3.2.1.GA

/**
 * BitacoraParam generated by hbm2java
 */
public class BitacoraParam implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private int bitacoraParamId;
	private Bitacora bitacora;
	private String paramNombre;
	private String paramValue;

	public BitacoraParam() {
	}

	public BitacoraParam(int bitacoraParamId, Bitacora bitacora) {
		this.bitacoraParamId = bitacoraParamId;
		this.bitacora = bitacora;
	}

	public BitacoraParam(int bitacoraParamId, Bitacora bitacora,
			String paramNombre, String paramValue) {
		this.bitacoraParamId = bitacoraParamId;
		this.bitacora = bitacora;
		this.paramNombre = paramNombre;
		this.paramValue = paramValue;
	}

	public int getBitacoraParamId() {
		return this.bitacoraParamId;
	}

	public void setBitacoraParamId(int bitacoraParamId) {
		this.bitacoraParamId = bitacoraParamId;
	}

	public Bitacora getBitacora() {
		return this.bitacora;
	}

	public void setBitacora(Bitacora bitacora) {
		this.bitacora = bitacora;
	}

	public String getParamNombre() {
		return this.paramNombre;
	}

	public void setParamNombre(String paramNombre) {
		this.paramNombre = paramNombre;
	}

	public String getParamValue() {
		return this.paramValue;
	}

	public void setParamValue(String paramValue) {
		this.paramValue = paramValue;
	}

}
