package com.adinfi.seven.business.domain;

// Generated 19/08/2013 10:38:14 AM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * CatAttrs generated by hbm2java
 */
public class CatAttrs implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private int catAttribId;
	private Attribs attribs;
	private Catalogs catalogs;
	private Character estatus;
	private Character required;
	private Character isUnique;
	private Integer catAttribIdRef = 0;
	private String extfkTName = null;
	private String extfkFName = null;

	private Set<CatRegValues> catRegValueses = new HashSet<CatRegValues>(0);

	public CatAttrs() {
	}

	public CatAttrs(int catAttribId, Attribs attribs, Catalogs catalogs) {
		this.catAttribId = catAttribId;
		this.attribs = attribs;
		this.catalogs = catalogs;
	}

	public CatAttrs(int catAttribId, Attribs attribs, Catalogs catalogs,
			Character estatus, Character required, Character isUnique,
			Set<CatRegValues> catRegValueses) {
		this.catAttribId = catAttribId;
		this.attribs = attribs;
		this.catalogs = catalogs;
		this.estatus = estatus;
		this.required = required;
		this.isUnique = isUnique;
		this.catRegValueses = catRegValueses;
	}

	public int getCatAttribId() {
		return this.catAttribId;
	}

	public void setCatAttribId(int catAttribId) {
		this.catAttribId = catAttribId;
	}

	public Attribs getAttribs() {
		return this.attribs;
	}

	public void setAttribs(Attribs attribs) {
		this.attribs = attribs;
	}

	public Catalogs getCatalogs() {
		return this.catalogs;
	}

	public void setCatalogs(Catalogs catalogs) {
		this.catalogs = catalogs;
	}

	public Character getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Character estatus) {
		this.estatus = estatus;
	}

	public Character getRequired() {
		return this.required;
	}

	public void setRequired(Character required) {
		this.required = required;
	}

	public Character getIsUnique() {
		return this.isUnique;
	}

	public void setIsUnique(Character isUnique) {
		this.isUnique = isUnique;
	}

	public Set<CatRegValues> getCatRegValueses() {
		return this.catRegValueses;
	}

	public void setCatRegValueses(Set<CatRegValues> catRegValueses) {
		this.catRegValueses = catRegValueses;
	}

	@Override
	public int hashCode() {
		int hash = 0;
		Integer id = Integer.valueOf(catAttribId);
		hash += id.hashCode();
		return hash;
	}

	@Override
	public boolean equals(Object o) {
		boolean bRet = false;
		if (o instanceof CatAttrs) {
			CatAttrs other = (CatAttrs) o;
			if (other.getAttribs() != null
					&& this.getAttribs() != null
					&& other.getCatalogs() != null
					&& this.getCatalogs() != null
					&& other.getCatalogs().getCatId() == this.getCatalogs()
							.getCatId()
					&& other.getAttribs().equals(this.getAttribs())) {
				bRet = true;
			}
		} else if (o instanceof CatViewControls) {
			CatViewControls other = (CatViewControls) o;
			if (other.getAttribId() == this.getAttribs().getAttribId()) {
				bRet = true;
			}
		}
		return bRet;
	}

	public void setCatAttribIdRef(Integer catAttribIdRef) {
		this.catAttribIdRef = catAttribIdRef;
	}

	public Integer getCatAttribIdRef() {
		return catAttribIdRef;
	}

	public String getExtfkTName() {
		return extfkTName;
	}

	public void setExtfkTName(String extfkTName) {
		this.extfkTName = extfkTName;
	}

	public String getExtfkFName() {
		return extfkFName;
	}

	public void setExtfkFName(String extfkFName) {
		this.extfkFName = extfkFName;
	}

}
