package com.adinfi.seven.business.domain;
// Generated Aug 18, 2016 6:51:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * CatFlujoAct generated by hbm2java
 */
public class CatFlujoAct  implements java.io.Serializable {


     private int id;
     private String nombre;
     private int diasantes;
     private Set<RelFlujoAct> relFlujoActs = new HashSet<RelFlujoAct>(0);

    public CatFlujoAct() {
    }

	
    public CatFlujoAct(int id) {
        this.id = id;
    }
    public CatFlujoAct(int id, String nombre, Set<RelFlujoAct> relFlujoActs) {
       this.id = id;
       this.nombre = nombre;
       this.relFlujoActs = relFlujoActs;
    }

    @Override
    public String toString() {
        return nombre;
    }

    @Override
    public boolean equals(Object object) {
        if (this == object) return true;
        if (object == null || getClass() != object.getClass()) return false;
        CatFlujoAct that = (CatFlujoAct) object;
        return id == that.id;
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }

    public int getDiasantes() {
        return diasantes;
    }

    public void setDiasantes(int diasantes) {
        this.diasantes = diasantes;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<RelFlujoAct> getRelFlujoActs() {
        return this.relFlujoActs;
    }
    
    public void setRelFlujoActs(Set<RelFlujoAct> relFlujoActs) {
        this.relFlujoActs = relFlujoActs;
    }




}


