package com.adinfi.seven.business.domain;
// Generated 10-ago-2015 17:57:09 by Hibernate Tools 4.3.1



/**
 * CatProveedor generated by hbm2java
 */
public class CatProveedor  implements java.io.Serializable {


     private int idProveedor;
     private String code;

    public CatProveedor() {
    }

	
    public CatProveedor(int idProveedor) {
        this.idProveedor = idProveedor;
    }
    public CatProveedor(int idProveedor, String code) {
       this.idProveedor = idProveedor;
       this.code = code;
    }
   
    public int getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(int idProveedor) {
        this.idProveedor = idProveedor;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }




}


