package com.adinfi.seven.business.domain;

/**
 * CatCategory generated by hbm2java
 */
public class CatSubCategory_bkp implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7766008631168397254L;

	private Integer subCategoryId;
	private String code;
	private CatCategory catCategory;

	public CatSubCategory_bkp() {
	}

	public CatSubCategory_bkp(Integer subCategoryId, String code,
			CatCategory catCategory) {
		super();
		this.subCategoryId = subCategoryId;
		this.code = code;
		this.catCategory = catCategory;
	}

	public Integer getSubCategoryId() {
		return subCategoryId;
	}

	public void setSubCategoryId(Integer subCategoryId) {
		this.subCategoryId = subCategoryId;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public CatCategory getCatCategory() {
		return catCategory;
	}

	public void setCatCategory(CatCategory catCategory) {
		this.catCategory = catCategory;
	}

	@Override
	public String toString() {
		return "CatSubCategory [subCategoryId=" + subCategoryId + ", code="
				+ code + ", catCategory=" + catCategory + "]";
	}

}
