package com.adinfi.seven.business.domain;
// Generated 10-ago-2015 17:57:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CatZone generated by hbm2java
 */
public class CatZone  implements java.io.Serializable {

     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idZone;
     private CatGZone catGZone;
     private CatTipoZona catTipoZona;
     private String code;
     private Set<RelZoneStore> relZoneStores = new HashSet<>(0);

    public CatZone() {
    }

	
    public CatZone(int idZone, CatGZone catGZone, CatTipoZona catTipoZona, String code) {
        this.idZone = idZone;
        this.catGZone = catGZone;
        this.catTipoZona = catTipoZona;
        this.code = code;
    }
    public CatZone(int idZone, CatGZone catGZone, CatTipoZona catTipoZona, String code, Set<RelZoneStore> relZoneStores) {
       this.idZone = idZone;
       this.catGZone = catGZone;
       this.catTipoZona = catTipoZona;
       this.code = code;
       this.relZoneStores = relZoneStores;
    }
   
    public int getIdZone() {
        return this.idZone;
    }
    
    public void setIdZone(int idZone) {
        this.idZone = idZone;
    }
    public CatGZone getCatGZone() {
        return this.catGZone;
    }
    
    public void setCatGZone(CatGZone catGZone) {
        this.catGZone = catGZone;
    }
    public CatTipoZona getCatTipoZona() {
        return this.catTipoZona;
    }
    
    public void setCatTipoZona(CatTipoZona catTipoZona) {
        this.catTipoZona = catTipoZona;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public Set<RelZoneStore> getRelZoneStores() {
        return this.relZoneStores;
    }
    
    public void setRelZoneStores(Set<RelZoneStore> relZoneStores) {
        this.relZoneStores = relZoneStores;
    }




}


