package com.adinfi.seven.business.domain;
// Generated Mar 28, 2016 4:39:34 PM by Hibernate Tools 4.3.1



/**
 * RelDisenoMecanica generated by hbm2java
 */
public class RelDisenoMecanica  implements java.io.Serializable {


     private RelDisenoMecanicaId id;
     private TblDisenos tblDisenos;
     private TblMecanica tblMecanica;
     private int preciosAuth;
     private String preciosComenta;
     private int categoryAuth;
     private String categoryComenta;

    public RelDisenoMecanica() {
    }

	
    public RelDisenoMecanica(RelDisenoMecanicaId id, TblDisenos tblDisenos, TblMecanica tblMecanica, int preciosAuth, int categoryAuth) {
        this.id = id;
        this.tblDisenos = tblDisenos;
        this.tblMecanica = tblMecanica;
        this.preciosAuth = preciosAuth;
        this.categoryAuth = categoryAuth;
    }
    public RelDisenoMecanica(RelDisenoMecanicaId id, TblDisenos tblDisenos, TblMecanica tblMecanica, int preciosAuth, String preciosComenta, int categoryAuth, String categoryComenta) {
       this.id = id;
       this.tblDisenos = tblDisenos;
       this.tblMecanica = tblMecanica;
       this.preciosAuth = preciosAuth;
       this.preciosComenta = preciosComenta;
       this.categoryAuth = categoryAuth;
       this.categoryComenta = categoryComenta;
    }
   
    public RelDisenoMecanicaId getId() {
        return this.id;
    }
    
    public void setId(RelDisenoMecanicaId id) {
        this.id = id;
    }
    public TblDisenos getTblDisenos() {
        return this.tblDisenos;
    }
    
    public void setTblDisenos(TblDisenos tblDisenos) {
        this.tblDisenos = tblDisenos;
    }
    public TblMecanica getTblMecanica() {
        return this.tblMecanica;
    }
    
    public void setTblMecanica(TblMecanica tblMecanica) {
        this.tblMecanica = tblMecanica;
    }
    public int getPreciosAuth() {
        return this.preciosAuth;
    }
    
    public void setPreciosAuth(int preciosAuth) {
        this.preciosAuth = preciosAuth;
    }
    public String getPreciosComenta() {
        return this.preciosComenta;
    }
    
    public void setPreciosComenta(String preciosComenta) {
        this.preciosComenta = preciosComenta;
    }
    public int getCategoryAuth() {
        return this.categoryAuth;
    }
    
    public void setCategoryAuth(int categoryAuth) {
        this.categoryAuth = categoryAuth;
    }
    public String getCategoryComenta() {
        return this.categoryComenta;
    }
    
    public void setCategoryComenta(String categoryComenta) {
        this.categoryComenta = categoryComenta;
    }




}


