package com.adinfi.seven.business.domain;
// Generated Mar 28, 2016 4:39:34 PM by Hibernate Tools 4.3.1



/**
 * RelDisenoMecanicaId generated by hbm2java
 */
public class RelDisenoMecanicaId  implements java.io.Serializable {


     private int mecanicaId;
     private int disenoId;

    public RelDisenoMecanicaId() {
    }

    public RelDisenoMecanicaId(int mecanicaId, int disenoId) {
       this.mecanicaId = mecanicaId;
       this.disenoId = disenoId;
    }
   
    public int getMecanicaId() {
        return this.mecanicaId;
    }
    
    public void setMecanicaId(int mecanicaId) {
        this.mecanicaId = mecanicaId;
    }
    public int getDisenoId() {
        return this.disenoId;
    }
    
    public void setDisenoId(int disenoId) {
        this.disenoId = disenoId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RelDisenoMecanicaId) ) return false;
		 RelDisenoMecanicaId castOther = ( RelDisenoMecanicaId ) other; 
         
		 return (this.getMecanicaId()==castOther.getMecanicaId())
 && (this.getDisenoId()==castOther.getDisenoId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getMecanicaId();
         result = 37 * result + this.getDisenoId();
         return result;
   }   


}


