package com.adinfi.seven.business.domain;
// Generated 31-ago-2015 21:53:45 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * RelItemStoreProveedor generated by hbm2java
 */
public class RelItemStoreProveedor  implements java.io.Serializable {


     private int id;
     private CatItem catItem;
     private CatProveedor catProveedor;
     private CatStore catStore;
     private BigDecimal costoActual;

    public RelItemStoreProveedor() {
    }

	
    public RelItemStoreProveedor(int id, CatItem catItem) {
        this.id = id;
        this.catItem = catItem;
    }
    public RelItemStoreProveedor(int id, CatItem catItem, CatProveedor catProveedor, CatStore catStore, BigDecimal costoActual) {
       this.id = id;
       this.catItem = catItem;
       this.catProveedor = catProveedor;
       this.catStore = catStore;
       this.costoActual = costoActual;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public CatItem getCatItem() {
        return this.catItem;
    }
    
    public void setCatItem(CatItem catItem) {
        this.catItem = catItem;
    }
    public CatProveedor getCatProveedor() {
        return this.catProveedor;
    }
    
    public void setCatProveedor(CatProveedor catProveedor) {
        this.catProveedor = catProveedor;
    }
    public CatStore getCatStore() {
        return this.catStore;
    }
    
    public void setCatStore(CatStore catStore) {
        this.catStore = catStore;
    }
    public BigDecimal getCostoActual() {
        return this.costoActual;
    }
    
    public void setCostoActual(BigDecimal costoActual) {
        this.costoActual = costoActual;
    }




}


