package com.adinfi.seven.business.domain;
// Generated 31-ago-2015 21:53:45 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * RelItemStore generated by hbm2java
 */
public class RelItemStore  implements java.io.Serializable {


     private int id;
     private CatItem catItem;
     private CatStore catStore;
     private BigDecimal precioAtual;
     private String margen;
     private BigDecimal existencia;
     private BigDecimal porcMargen;
     private int idrelitemstore;
     private BigDecimal impuesto;

    public RelItemStore() {
    }

	
    public RelItemStore(int id, int idrelitemstore) {
        this.id = id;
        this.idrelitemstore = idrelitemstore;
    }
    public RelItemStore(int id, CatItem catItem, CatStore catStore, BigDecimal precioAtual, String margen, BigDecimal existencia, BigDecimal porcMargen, int idrelitemstore) {
       this.id = id;
       this.catItem = catItem;
       this.catStore = catStore;
       this.precioAtual = precioAtual;
       this.margen = margen;
       this.existencia = existencia;
       this.porcMargen = porcMargen;
       this.idrelitemstore = idrelitemstore;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public CatItem getCatItem() {
        return this.catItem;
    }
    
    public void setCatItem(CatItem catItem) {
        this.catItem = catItem;
    }
    public CatStore getCatStore() {
        return this.catStore;
    }
    
    public void setCatStore(CatStore catStore) {
        this.catStore = catStore;
    }
    public BigDecimal getPrecioAtual() {
        return this.precioAtual;
    }
    
    public void setPrecioAtual(BigDecimal precioAtual) {
        this.precioAtual = precioAtual;
    }
    public String getMargen() {
        return this.margen;
    }
    
    public void setMargen(String margen) {
        this.margen = margen;
    }
    public BigDecimal getExistencia() {
        return this.existencia;
    }
    
    public void setExistencia(BigDecimal existencia) {
        this.existencia = existencia;
    }
    public BigDecimal getPorcMargen() {
        return this.porcMargen;
    }
    
    public void setPorcMargen(BigDecimal porcMargen) {
        this.porcMargen = porcMargen;
    }
    public int getIdrelitemstore() {
        return this.idrelitemstore;
    }
    
    public void setIdrelitemstore(int idrelitemstore) {
        this.idrelitemstore = idrelitemstore;
    }

    /**
     * @return the impuesto
     */
    public BigDecimal getImpuesto() {
        return impuesto;
    }

    /**
     * @param impuesto the impuesto to set
     */
    public void setImpuesto(BigDecimal impuesto) {
        this.impuesto = impuesto;
    }




}


