package com.adinfi.seven.business.domain;
// Generated Sep 29, 2014 11:31:29 AM by Hibernate Tools 3.6.0



/**
 * RelZona generated by hbm2java
 */
public class RelZona  implements java.io.Serializable {


     private int zonaId;
     private TblMecanica tblMecanica;

    public RelZona() {
    }

    public RelZona(int zonaId, TblMecanica tblMecanica) {
       this.zonaId = zonaId;
       this.tblMecanica = tblMecanica;
    }
   
    public int getZonaId() {
        return this.zonaId;
    }
    
    public void setZonaId(int zonaId) {
        this.zonaId = zonaId;
    }
    public TblMecanica getTblMecanica() {
        return this.tblMecanica;
    }
    
    public void setTblMecanica(TblMecanica tblMecanica) {
        this.tblMecanica = tblMecanica;
    }




}


