package com.adinfi.seven.business.domain;
// Generated 17/02/2014 06:21:18 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * TblArchivoArticulo generated by hbm2java
 */
public class TblArchivoArticulo  implements java.io.Serializable {

	private static final long serialVersionUID = -3002118015000601958L;
	private int idArchivoArticulo;
     private int idHoja;
     private int segmentId;
     private String pathArchivo;
     private Date fechaAlta;

    public TblArchivoArticulo() {
    }

    public TblArchivoArticulo(int idArchivoArticulo, int idHoja, int segmentId, String pathArchivo, Date fechaAlta) {
       this.idArchivoArticulo = idArchivoArticulo;
       this.idHoja = idHoja;
       this.segmentId = segmentId;
       this.pathArchivo = pathArchivo;
       this.fechaAlta = fechaAlta;
    }
   
    public int getIdArchivoArticulo() {
        return this.idArchivoArticulo;
    }
    
    public void setIdArchivoArticulo(int idArchivoArticulo) {
        this.idArchivoArticulo = idArchivoArticulo;
    }
    public int getIdHoja() {
        return this.idHoja;
    }
    
    public void setIdHoja(int idHoja) {
        this.idHoja = idHoja;
    }
    public int getSegmentId() {
        return this.segmentId;
    }
    
    public void setSegmentId(int segmentId) {
        this.segmentId = segmentId;
    }
    public String getPathArchivo() {
        return this.pathArchivo;
    }
    
    public void setPathArchivo(String pathArchivo) {
        this.pathArchivo = pathArchivo;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }




}


