package com.adinfi.seven.business.domain;
// Generated 14/02/2014 05:08:14 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * TblComentarioArticulo generated by hbm2java
 */
public class TblComentarioArticulo  implements java.io.Serializable {

	private static final long serialVersionUID = -6873814322083780532L;
	private int idComentarioArticulo;
     private int segmentId;
     private String comentario;
     private Date fechaAlta;
     private int idHoja;

    public TblComentarioArticulo() {
    }

    public TblComentarioArticulo(int idComentarioArticulo, int segmentId, String comentario, Date fechaAlta, int idHoja) {
       this.idComentarioArticulo = idComentarioArticulo;
       this.segmentId = segmentId;
       this.comentario = comentario;
       this.fechaAlta = fechaAlta;
       this.idHoja = idHoja;
    }
   
    public int getIdComentarioArticulo() {
        return this.idComentarioArticulo;
    }
    
    public void setIdComentarioArticulo(int idComentarioArticulo) {
        this.idComentarioArticulo = idComentarioArticulo;
    }
    public int getSegmentId() {
        return this.segmentId;
    }
    
    public void setSegmentId(int segmentId) {
        this.segmentId = segmentId;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public int getIdHoja() {
        return this.idHoja;
    }
    
    public void setIdHoja(int idHoja) {
        this.idHoja = idHoja;
    }




}


