package com.adinfi.seven.business.domain;
// Generated Mar 21, 2016 4:56:19 PM by Hibernate Tools 4.3.1


import java.sql.Blob;
import java.util.HashSet;
import java.util.Set;

/**
 * TblDisenos generated by hbm2java
 */
public class TblDisenos  implements java.io.Serializable {


    private int disenoId;
    private TblMecanica tblMecanica;
    private int programaId;
    private Blob image;
    private Integer preciosAuth;
    private String preciosComenta;
    private Integer categoryAuth;
    private String categoryComenta;
    private Integer estatusPrecios;
    private Set<RelDisenoSenal> relDisenoSenals = new HashSet<RelDisenoSenal>(0);
    private Set<RelDisenoMecanica> relDisenoMecanicas = new HashSet<RelDisenoMecanica>(0);
    private Set<RelGrupoZonaDiseno> grupoZonaLst;
    private Set<RelZonaDiseno> zonaLst;
    private Set<RelStoreDiseno> storeLst;

    public TblDisenos() {
    }


    public TblDisenos(int disenoId, TblMecanica tblMecanica, int programaId, Blob image) {
        this.disenoId = disenoId;
        this.tblMecanica = tblMecanica;
        this.programaId = programaId;
        this.image = image;
    }
    public TblDisenos(int disenoId, TblMecanica tblMecanica, int programaId, Blob image, Integer preciosAuth, String preciosComenta, Integer categoryAuth, String categoryComenta, Integer estatusPrecios, Set<RelDisenoSenal> relDisenoSenals, Set<RelDisenoMecanica> relDisenoMecanicas) {
        this.disenoId = disenoId;
        this.tblMecanica = tblMecanica;
        this.programaId = programaId;
        this.image = image;
        this.preciosAuth = preciosAuth;
        this.preciosComenta = preciosComenta;
        this.categoryAuth = categoryAuth;
        this.categoryComenta = categoryComenta;
        this.estatusPrecios = estatusPrecios;
        this.relDisenoSenals = relDisenoSenals;
        this.relDisenoMecanicas = relDisenoMecanicas;
    }

    public int getDisenoId() {
        return this.disenoId;
    }

    public void setDisenoId(int disenoId) {
        this.disenoId = disenoId;
    }
    public TblMecanica getTblMecanica() {
        return this.tblMecanica;
    }

    public void setTblMecanica(TblMecanica tblMecanica) {
        this.tblMecanica = tblMecanica;
    }
    public int getProgramaId() {
        return this.programaId;
    }

    public void setProgramaId(int programaId) {
        this.programaId = programaId;
    }
    public Blob getImage() {
        return this.image;
    }

    public void setImage(Blob image) {
        this.image = image;
    }
    public Integer getPreciosAuth() {
        return this.preciosAuth;
    }

    public void setPreciosAuth(Integer preciosAuth) {
        this.preciosAuth = preciosAuth;
    }
    public String getPreciosComenta() {
        return this.preciosComenta;
    }

    public void setPreciosComenta(String preciosComenta) {
        this.preciosComenta = preciosComenta;
    }
    public Integer getCategoryAuth() {
        return this.categoryAuth;
    }

    public void setCategoryAuth(Integer categoryAuth) {
        this.categoryAuth = categoryAuth;
    }
    public String getCategoryComenta() {
        return this.categoryComenta;
    }

    public void setCategoryComenta(String categoryComenta) {
        this.categoryComenta = categoryComenta;
    }
    public Integer getEstatusPrecios() {
        return this.estatusPrecios;
    }

    public void setEstatusPrecios(Integer estatusPrecios) {
        this.estatusPrecios = estatusPrecios;
    }
    public Set<RelDisenoSenal> getRelDisenoSenals() {
        return this.relDisenoSenals;
    }

    public void setRelDisenoSenals(Set<RelDisenoSenal> relDisenoSenals) {
        this.relDisenoSenals = relDisenoSenals;
    }
    public Set<RelDisenoMecanica> getRelDisenoMecanicas() {
        return this.relDisenoMecanicas;
    }

    public void setRelDisenoMecanicas(Set<RelDisenoMecanica> relDisenoMecanicas) {
        this.relDisenoMecanicas = relDisenoMecanicas;
    }

    public Set<RelGrupoZonaDiseno> getGrupoZonaLst() {
        return grupoZonaLst;
    }

    public void setGrupoZonaLst(Set<RelGrupoZonaDiseno> grupoZonaLst) {
        this.grupoZonaLst = grupoZonaLst;
    }

    public Set<RelZonaDiseno> getZonaLst() {
        return zonaLst;
    }

    public void setZonaLst(Set<RelZonaDiseno> zonaLst) {
        this.zonaLst = zonaLst;
    }

    public Set<RelStoreDiseno> getStoreLst() {
        return storeLst;
    }

    public void setStoreLst(Set<RelStoreDiseno> storeLst) {
        this.storeLst = storeLst;
    }
}


