package com.adinfi.seven.business.domain;
// Generated 13-mar-2014 17:17:22 by Hibernate Tools 3.6.0

/**
 * TblDisenoPromoCm generated by hbm2java
 */
public class TblDisenoPromoCm  implements java.io.Serializable {

	 private long id;
     private String pid;
     private long idCampana;
     private int idPrograma;

    public TblDisenoPromoCm() {
    }

    public TblDisenoPromoCm(long id, String pid, long idCampana, int idPrograma) {
       this.id = id;
       this.pid = pid;
       this.idCampana = idCampana;
       this.idPrograma = idPrograma;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getPid() {
        return this.pid;
    }
    
    public void setPid(String pid) {
        this.pid = pid;
    }
    public long getIdCampana() {
        return this.idCampana;
    }
    
    public void setIdCampana(long idCampana) {
        this.idCampana = idCampana;
    }
    public int getIdPrograma() {
        return this.idPrograma;
    }
    
    public void setIdPrograma(int idPrograma) {
        this.idPrograma = idPrograma;
    }
}