package com.adinfi.seven.business.domain;
// Generated 16/01/2014 10:20:42 AM by Hibernate Tools 3.2.1.GA



/**
 * TblPrensaSistemaVenta generated by hbm2java
 */
public class TblPrensaSistemaVenta  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 6547804607102779911L;
	private TblPrensaSistemaVentaId id;
     private TblPrensa tblPrensa;

    public TblPrensaSistemaVenta() {
    }

    public TblPrensaSistemaVenta(TblPrensaSistemaVentaId id, TblPrensa tblPrensa) {
       this.id = id;
       this.tblPrensa = tblPrensa;
    }
   
    public TblPrensaSistemaVentaId getId() {
        return this.id;
    }
    
    public void setId(TblPrensaSistemaVentaId id) {
        this.id = id;
    }
    public TblPrensa getTblPrensa() {
        return this.tblPrensa;
    }
    
    public void setTblPrensa(TblPrensa tblPrensa) {
        this.tblPrensa = tblPrensa;
    }




}


