package com.adinfi.seven.business.domain;
// Generated 31/01/2014 04:48:00 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TblPreciosFolleto generated by hbm2java
 */
public class TblPreciosFolleto  implements java.io.Serializable {


     private int idPrecFolleto;
     private TblFolleto tblFolleto;
     private Date fechaCarga;
     private String fileName;
     private Set tblPreciosFolletoDets = new HashSet(0);

    public TblPreciosFolleto() {
    }

	
    public TblPreciosFolleto(int idPrecFolleto, TblFolleto tblFolleto, Date fechaCarga, String fileName) {
        this.idPrecFolleto = idPrecFolleto;
        this.tblFolleto = tblFolleto;
        this.fechaCarga = fechaCarga;
        this.fileName = fileName;
    }
    public TblPreciosFolleto(int idPrecFolleto, TblFolleto tblFolleto, Date fechaCarga, String fileName, Set tblPreciosFolletoDets) {
       this.idPrecFolleto = idPrecFolleto;
       this.tblFolleto = tblFolleto;
       this.fechaCarga = fechaCarga;
       this.fileName = fileName;
       this.tblPreciosFolletoDets = tblPreciosFolletoDets;
    }
   
    public int getIdPrecFolleto() {
        return this.idPrecFolleto;
    }
    
    public void setIdPrecFolleto(int idPrecFolleto) {
        this.idPrecFolleto = idPrecFolleto;
    }
    public TblFolleto getTblFolleto() {
        return this.tblFolleto;
    }
    
    public void setTblFolleto(TblFolleto tblFolleto) {
        this.tblFolleto = tblFolleto;
    }
    public Date getFechaCarga() {
        return this.fechaCarga;
    }
    
    public void setFechaCarga(Date fechaCarga) {
        this.fechaCarga = fechaCarga;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public Set getTblPreciosFolletoDets() {
        return this.tblPreciosFolletoDets;
    }
    
    public void setTblPreciosFolletoDets(Set tblPreciosFolletoDets) {
        this.tblPreciosFolletoDets = tblPreciosFolletoDets;
    }




}


