package com.adinfi.seven.business.domain;
// Generated Sep 29, 2014 11:31:29 AM by Hibernate Tools 3.6.0



/**
 * TblSenalamientos generated by hbm2java
 */
public class TblSenalamientos  implements java.io.Serializable {


     private int senalamientoId;
     private TblMecanica tblMecanica;
     private String nombreSenal;

    public TblSenalamientos() {
    }

	
    public TblSenalamientos(int senalamientoId, TblMecanica tblMecanica) {
        this.senalamientoId = senalamientoId;
        this.tblMecanica = tblMecanica;
    }
    public TblSenalamientos(int senalamientoId, TblMecanica tblMecanica, String nombreSenal) {
       this.senalamientoId = senalamientoId;
       this.tblMecanica = tblMecanica;
       this.nombreSenal = nombreSenal;
    }
   
    public int getSenalamientoId() {
        return this.senalamientoId;
    }
    
    public void setSenalamientoId(int senalamientoId) {
        this.senalamientoId = senalamientoId;
    }
    public TblMecanica getTblMecanica() {
        return this.tblMecanica;
    }
    
    public void setTblMecanica(TblMecanica tblMecanica) {
        this.tblMecanica = tblMecanica;
    }
    public String getNombreSenal() {
        return this.nombreSenal;
    }
    
    public void setNombreSenal(String nombreSenal) {
        this.nombreSenal = nombreSenal;
    }




}


