package com.adinfi.seven.business.domain;
// Generated 10/01/2014 12:26:09 PM by Hibernate Tools 3.6.0



/**
 * TblTemplateUser generated by hbm2java
 */
public class TblTemplateUser  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 6457362294474221709L;
	private int idTemplateUser;
     private TblTemplate tblTemplate;
     private int idUser;
     private int idCategory;

    public TblTemplateUser() {
    }

    public TblTemplateUser(TblTemplate tblTemplate, int idUser, int idCategory) {
        this.tblTemplate = tblTemplate;
        this.idUser = idUser;
        this.idCategory = idCategory;
     }
    
    public TblTemplateUser(int idTemplateUser, TblTemplate tblTemplate, int idUser, int idCategory) {
       this.idTemplateUser = idTemplateUser;
       this.tblTemplate = tblTemplate;
       this.idUser = idUser;
       this.idCategory = idCategory;
    }
   
    public int getIdTemplateUser() {
        return this.idTemplateUser;
    }
    
    public void setIdTemplateUser(int idTemplateUser) {
        this.idTemplateUser = idTemplateUser;
    }
    public TblTemplate getTblTemplate() {
        return this.tblTemplate;
    }
    
    public void setTblTemplate(TblTemplate tblTemplate) {
        this.tblTemplate = tblTemplate;
    }
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }
    public int getIdCategory() {
        return this.idCategory;
    }
    
    public void setIdCategory(int idCategory) {
        this.idCategory = idCategory;
    }




}


