package com.adinfi.seven.business.domain;
// Generated 10/01/2014 12:26:09 PM by Hibernate Tools 3.6.0



/**
 * TblTemplateSegments generated by hbm2java
 */
public class TblTemplateSegments  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1855960863051845365L;
	private int segmentId;
     private TblTemplate tblTemplate;
     private Integer segmentParentId;
     private int width;
     private Integer height;
     private Character tipo;
     private Character isPercentage;
     private Character elemEq;
     private String segName;
     private int templateChildId;
     private TblTemplate templateChild;

    public TblTemplateSegments() {
    }

	
    public TblTemplateSegments(int segmentId, TblTemplate tblTemplate, int width, int templateChildId) {
        this.segmentId = segmentId;
        this.tblTemplate = tblTemplate;
        this.width = width;
        this.templateChildId = templateChildId;
    }
    
    public TblTemplateSegments(TblTemplate tblTemplate, Integer segmentParentId, int width, Integer height, Character tipo, Character isPercentage, Character elemEq, String segName, int templateChildId) {
        this.tblTemplate = tblTemplate;
        this.segmentParentId = segmentParentId;
        this.width = width;
        this.height = height;
        this.tipo = tipo;
        this.isPercentage = isPercentage;
        this.elemEq = elemEq;
        this.segName = segName;
        this.templateChildId = templateChildId;
     }
    
    public TblTemplateSegments(int segmentId, TblTemplate tblTemplate, Integer segmentParentId, int width, Integer height, Character tipo, Character isPercentage, Character elemEq, String segName, int templateChildId) {
       this.segmentId = segmentId;
       this.tblTemplate = tblTemplate;
       this.segmentParentId = segmentParentId;
       this.width = width;
       this.height = height;
       this.tipo = tipo;
       this.isPercentage = isPercentage;
       this.elemEq = elemEq;
       this.segName = segName;
       this.templateChildId = templateChildId;
    }
   
    public int getSegmentId() {
        return this.segmentId;
    }
    
    public void setSegmentId(int segmentId) {
        this.segmentId = segmentId;
    }
    public TblTemplate getTblTemplate() {
        return this.tblTemplate;
    }
    
    public void setTblTemplate(TblTemplate tblTemplate) {
        this.tblTemplate = tblTemplate;
    }
    public Integer getSegmentParentId() {
        return this.segmentParentId;
    }
    
    public void setSegmentParentId(Integer segmentParentId) {
        this.segmentParentId = segmentParentId;
    }
    public int getWidth() {
        return this.width;
    }
    
    public void setWidth(int width) {
        this.width = width;
    }
    public Integer getHeight() {
        return this.height;
    }
    
    public void setHeight(Integer height) {
        this.height = height;
    }
    public Character getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Character tipo) {
        this.tipo = tipo;
    }
    public Character getIsPercentage() {
        return this.isPercentage;
    }
    
    public void setIsPercentage(Character isPercentage) {
        this.isPercentage = isPercentage;
    }
    public Character getElemEq() {
        return this.elemEq;
    }
    
    public void setElemEq(Character elemEq) {
        this.elemEq = elemEq;
    }
    public String getSegName() {
        return this.segName;
    }
    
    public void setSegName(String segName) {
        this.segName = segName;
    }
    public int getTemplateChildId() {
        return this.templateChildId;
    }
    
    public void setTemplateChildId(int templateChildId) {
        this.templateChildId = templateChildId;
    }


	public TblTemplate getTemplateChild() {
		return templateChild;
	}


	public void setTemplateChild(TblTemplate templateChild) {
		this.templateChild = templateChild;
	}




}


