package com.adinfi.seven.business.domain;
// Generated 10/01/2014 12:26:09 PM by Hibernate Tools 3.6.0


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;

/**
 * TblTemplate generated by hbm2java
 */
public class TblTemplate  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 5856007939244763703L;
	private int templateId;
     private String templateName;
     private int width;
     private int height;
     private String status;
     private Date fechaCreacion;
     private String tipoLayout;
     private String pathHead;
     private String pathFoot;
     private Set<TblTemplateUser> tblTemplateUsers = new HashSet<TblTemplateUser>(0);
   //  private Set<TblTemplateSegments> tblTemplateSegmentses = new HashSet<TblTemplateSegments>(0);
     private List<TblTemplateSegments> tblTemplateSegments ;
     private Map<Integer, List< TblTemplateSegments> > mapSegmentsByParent;
     private Map<Integer, TblTemplateSegments > mapSegmentsById;
     private Integer rootSegmentId;
     private TblTemplateSegments rootSection;

     
     
     
    public Integer getRootSegmentId() {
		return rootSegmentId;
	}


	public void setRootSegmentId(Integer rootSegmentId) {
		this.rootSegmentId = rootSegmentId;
	}


	public Map<Integer, List<TblTemplateSegments>> getMapSegmentsByParent() {
		return mapSegmentsByParent;
	}


	public void setMapSegmentsByParent(
			Map<Integer, List<TblTemplateSegments>> mapSegmentsByParent) {
		this.mapSegmentsByParent = mapSegmentsByParent;
	}


	public Map<Integer, TblTemplateSegments> getMapSegmentsById() {
		return mapSegmentsById;
	}


	public void setMapSegmentsById(Map<Integer, TblTemplateSegments> mapSegmentsById) {
		this.mapSegmentsById = mapSegmentsById;
	}


	public List<TblTemplateSegments> getTblTemplateSegments() {
		return tblTemplateSegments;
	}


	public void setTblTemplateSegments(List<TblTemplateSegments> tblTemplateSegments) {
		this.tblTemplateSegments = tblTemplateSegments;
		genMaps();
	}


	public TblTemplate() {
    }

	
    public TblTemplate(int templateId, String templateName, int width, int height, Date fechaCreacion, String tipoLayout) {
        this.templateId = templateId;
        this.templateName = templateName;
        this.width = width;
        this.height = height;
        this.fechaCreacion = fechaCreacion;
        this.tipoLayout = tipoLayout;
    }
    
    public TblTemplate(String templateName, int width, int height, String status, Date fechaCreacion, String tipoLayout, Set<TblTemplateUser> tblTemplateUsers, Set<TblTemplateSegments> tblTemplateSegmentses) {
        this.templateName = templateName;
        this.width = width;
        this.height = height;
        this.status = status;
        this.fechaCreacion = fechaCreacion;
        this.tipoLayout = tipoLayout;
        this.tblTemplateUsers = tblTemplateUsers;
       // this.tblTemplateSegmentses = tblTemplateSegmentses;
     }
    
    public TblTemplate(int templateId, String templateName, int width, int height, String status, Date fechaCreacion, String tipoLayout, Set<TblTemplateUser> tblTemplateUsers, Set<TblTemplateSegments> tblTemplateSegmentses) {
       this.templateId = templateId;
       this.templateName = templateName;
       this.width = width;
       this.height = height;
       this.status = status;
       this.fechaCreacion = fechaCreacion;
       this.tipoLayout = tipoLayout;
       this.tblTemplateUsers = tblTemplateUsers;
     //  this.tblTemplateSegmentses = tblTemplateSegmentses;
    }
   
    public int getTemplateId() {
        return this.templateId;
    }
    
    public void setTemplateId(int templateId) {
        this.templateId = templateId;
        
    }
    public String getTemplateName() {
        return this.templateName;
    }
    
    public void setTemplateName(String templateName) {
        this.templateName = templateName;
    }
    public int getWidth() {
        return this.width;
    }
    
    public void setWidth(int width) {
        this.width = width;
    }
    public int getHeight() {
        return this.height;
    }
    
    public void setHeight(int height) {
        this.height = height;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getTipoLayout() {
        return this.tipoLayout;
    }
    
    public void setTipoLayout(String tipoLayout) {
        this.tipoLayout = tipoLayout;
    }
    public String getPathHead() {
        return this.pathHead;
    }
    
    public void setPathHead(String pathHead) {
        this.pathHead = pathHead;
    }
    public String getPathFoot() {
        return this.pathFoot;
    }
    
    public void setPathFoot(String pathFoot) {
        this.pathFoot = pathFoot;
    }
    public Set<TblTemplateUser> getTblTemplateUsers() {
        return this.tblTemplateUsers;
    }
    
    public void setTblTemplateUsers(Set<TblTemplateUser> tblTemplateUsers) {
        this.tblTemplateUsers = tblTemplateUsers;
    }
    
    protected void genMaps(){
    	mapSegmentsById=null;
    	mapSegmentsByParent=null;
    	if(tblTemplateSegments==null || tblTemplateSegments.size()<=0 ) {
    		return;
    	}
    	
    	mapSegmentsByParent=new TreeMap<Integer, List<TblTemplateSegments>>();
    	mapSegmentsById=new TreeMap<Integer, TblTemplateSegments>();
    	
    	List<TblTemplateSegments> arrTmp;
    	for( TblTemplateSegments segment :  tblTemplateSegments ){
    		if(segment.getSegmentParentId()==0){
    			this.rootSegmentId=segment.getSegmentId();
    			this.rootSection=segment;
    		}
    		arrTmp=mapSegmentsByParent.get(segment.getSegmentParentId());
    		if(arrTmp==null){
    			arrTmp=new ArrayList<TblTemplateSegments>();
    			mapSegmentsByParent.put(segment.getSegmentParentId(), arrTmp);
    		}
    		arrTmp.add(segment);
    		
    		mapSegmentsById.put(segment.getSegmentId(), segment);    		
    		
    	}
    	
    	
    	
    	
    	
    	
    	
    	
    	
    	
    	
    	
    }


	public TblTemplateSegments getRootSection() {
		return rootSection;
	}


	public void setRootSection(TblTemplateSegments rootSection) {
		this.rootSection = rootSection;
	}


}


