package com.adinfi.seven.business.domain;

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * CatEstatus generated by hbm2java
 */
public class CatEstatus implements java.io.Serializable {

    private int idestatus;
    private String nombre;
    private Set<TblCampanaActividades> tblCampanaActividadeses = new HashSet<TblCampanaActividades>(0);
    private Set<TblActividad> tblActividads = new HashSet<TblActividad>(0);

    public CatEstatus() {
    }

    public CatEstatus(int idestatus, String nombre) {
        this.idestatus = idestatus;
        this.nombre = nombre;
    }

    public CatEstatus(int idestatus, String nombre, Set<TblCampanaActividades> tblCampanaActividadeses,
                      Set<TblActividad> tblActividads) {
        this.idestatus = idestatus;
        this.nombre = nombre;
        this.tblCampanaActividadeses = tblCampanaActividadeses;
        this.tblActividads = tblActividads;
    }

    @Override
    public boolean equals(Object object) {
        if (this == object) return true;
        if (object == null || getClass() != object.getClass()) return false;
        CatEstatus estatus = (CatEstatus) object;
        return idestatus == estatus.idestatus;
    }

    @Override
    public int hashCode() {
        return Objects.hash(idestatus);
    }

    @Override
    public String toString() {
        return nombre;
    }

    public int getIdestatus() {
        return this.idestatus;
    }

    public void setIdestatus(int idestatus) {
        this.idestatus = idestatus;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Set<TblCampanaActividades> getTblCampanaActividadeses() {
        return this.tblCampanaActividadeses;
    }

    public void setTblCampanaActividadeses(Set<TblCampanaActividades> tblCampanaActividadeses) {
        this.tblCampanaActividadeses = tblCampanaActividadeses;
    }

    public Set<TblActividad> getTblActividads() {
        return this.tblActividads;
    }

    public void setTblActividads(Set<TblActividad> tblActividads) {
        this.tblActividads = tblActividads;
    }

}
